defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
      #default values for meta tags. can be configured per page in each template
      title: "JBCNConf - The first Java and JVM conference in Spain"
      description: "The first big Java and JVM conference in Spain. Barcelona will host this great event next 16th and 18th of June 2017. 3 days to share knowledge and experiences, to meet enthusiasts and geeks, and to learn about new technologies."
      keywords: "java barcelona, jug barcelona, jbcnconf, java barcelona conference"
source: "2017"